### ISSUE TITLE
Refactor the Structure of NanoTorch Deep Learning Library From Scratch

### ISSUE THREAD

**Issue by JamorMoussa** [JamorMoussa/NanoTorch-DeepLearning-Library-From-Scratch#9]
### Refactor Repository Structure
I suggest restructuring the repository by creating a `docs` folder to house future documentation for the library. This involves moving existing markdown files like `new_features.md` and `git_logs.md` to the `docs` folder. Additionally, I propose removing the `test.py` file. Also, move `main.py` to the folder `test`.

**Comment by anas1IA** [comment]
Got it
